### ISSUE TITLE
Build fails: fixx11h.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [Alexander-r/qtvkbd#1]
It fails to build on Archlinux with Kde Plasma 5. It search for /usr/include/fixx11h.h which is part of https://www.archlinux.org/packages/extra/x86_64/kdelibs/

On Plasma 5 this file is in /usr/include/KF5/KWindowSystem/fixx11h.h which is part of https://www.archlinux.org/packages/extra/x86_64/kwindowsystem/

I think libraries path could be set in CMakeLists.txt  similiar as here https://github.com/papylhomme/diskmonitor/issues/12#issuecomment-113404180

**Comment by Alexander-r** [comment]
Thanks for the report. I didn't notice that fixx11h.h was part of kdelibs.
It seems that with Qt5 this is not needed. For me everything builds and works fine without it.
Please check if c25f34cb74c0b44e8bc67273edde7725151e0087 works for you.

**Comment by ghost** [comment]
Now it works, thank you!
