### ISSUE TITLE
Start "minimized"?

### ISSUE THREAD

**Issue by kokoko3k** [Alexander-r/qtvkbd#4]
Hi.
By now, im unable to make qtvkbd to start minimized, and any time the computer boots, it pops up (autostarted).
Is there a way to make it happen? Thanks!

**Comment by Alexander-r** [comment]
In v0.8.2 I've added an option to start application minimized.
To do so you have to start it with `-m` or `--minimized` option:
`qtvkbd -m`

**Comment by kokoko3k** [comment]
It does work indeed, many thanks!
