### ISSUE TITLE
autostart minimized or disable autostart

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [Alexander-r/qtvkbd#6]
Is there a chance to start the application in the tray on startup or disable the autostart?

I did a install from the aur, here:
https://aur.archlinux.org/packages/qtvkbd/

My machine: 4.19.85-1-MAJARO with kde-plasma

**Comment by Alexander-r** [comment]
You can add `-m` option to start the keyboard minimized to tray.
Version 0.8.3 also saves and restores last minimized state. So if the keyboard was minimized it will also be minimized the next time you start it.
