### ISSUE TITLE
qtvkbd and wayland

### ISSUE THREAD

**Issue by Tuxman2** [Alexander-r/qtvkbd#8]
Hello,

I'm using qtvkbd under kde plasma 5.18. It works very well with Xorg/X11 but I would like to use it under Wayland. The problem is qtvkbd don't start under Wayland (segmentation fault). Is there a way to use qtvkbd under Wayland ? Perhaps with the help of Xwayland ? 

Thanks.

**Comment by Tuxman2** [comment]
Hi,

Thanks for this software. It is a fantastic software (better than the default virtual keyboard).

Can you port your program to Wayland ? It works very well on Xorg but not in Wayland. It will be great if you can do that. 

Thanks.

**Comment by Alexander-r** [comment]
Closing the issue in favor of https://github.com/Alexander-r/qtvkbd/issues/11
